/* global React */
const PROJECTS = [
  { id:'jobtailor', eyebrow:'LIVE DEMO · 2026', status:'shipping', href:'#tailor',
    title:'JobBoating — resume tailored to a job description',
    desc:'Paste a JD + your resume; get a rewritten resume that surfaces relevant experience — Groq (llama-3.3-70b) with a no-fabrication guardrail. Try it live.',
    tags:['llm','groq','ruby','react','live-demo'] },
  { id:'scheduler', eyebrow:'LIVE DEMO · 2026', status:'shipping', href:'#scheduler',
    title:'Tnufa scheduler — 40-hour week under company flexibility',
    desc:'Interactive weekly grid: allocate 40 hours across deep work, meetings, admin, and focus while satisfying core hours and per-day minimums. From the Tnufa infrastructure.',
    tags:['scheduling','react','sinatra','live-demo'] },
  { id:'tnufa', repo:'Tnufa', eyebrow:'PROJECT · 2025', status:'shipping',
    title:'Tnufa — workforce mobility, reimagined',
    desc:'A platform for skill-based career mobility. Maps people to roles using embeddings over real career trajectories — not job-board keywords. Live at tnufa.ai.',
    tags:['typescript','llm','retrieval','product'] },
  { id:'xgitguard', repo:'xGitGuard', eyebrow:'PROJECT · 2024', status:'shipped',
    title:'xGitGuard — secret-leak detector for GitHub',
    desc:'Continuously scans public commits for leaked credentials, API keys, and tokens. ML-assisted classifier cuts false positives by ~70% versus regex-only baselines.',
    tags:['python','security','ml'] },
  { id:'noshsource', repo:'NoshSorce', eyebrow:'PROJECT · 2024', status:'shipped',
    title:'NoshSource — cloud-kitchen ops platform',
    desc:'MERN-stack ops layer for cloud kitchens: orders, inventory, and AWS-Kinesis-streamed real-time updates. Powered 5,000+ daily users in production at Burpez.',
    tags:['mern','aws','redux','realtime'] },
  { id:'gpt-codemaker', repo:'gpt-CodeMaker', eyebrow:'PROJECT · 2024', status:'shipped',
    title:'gpt-CodeMaker — codegen agent',
    desc:'LLM-driven code generation with structured output, function-tool calling, and a small repair loop. Fast scaffolding for repeatable boilerplate.',
    tags:['llm','agents','typescript'] },
  { id:'serverless-api', repo:'serverless-api', eyebrow:'PROJECT · 2023', status:'shipped',
    title:'serverless-api — production REST on AWS',
    desc:'A reference implementation for shipping REST APIs on Lambda + API Gateway + DynamoDB with blue/green CodeDeploy. Patterns I battle-tested at Vanguard.',
    tags:['aws','lambda','dynamodb','iac'] },
  { id:'terraform-aws-ecs', repo:'terraform-aws-ecs', eyebrow:'PROJECT · 2023', status:'shipped',
    title:'terraform-aws-ecs — opinionated ECS module',
    desc:'A reusable Terraform module for ECS Fargate services with sane defaults: blue/green, autoscaling, log shipping, and least-privilege IAM out of the box.',
    tags:['terraform','aws','ecs','iac'] },
  { id:'webscrapergo', repo:'WebScraperGo', eyebrow:'PROJECT · 2023', status:'shipped',
    title:'WebScraperGo — concurrent scraper in Go',
    desc:'Polite crawler with worker pools, robots.txt respect, and back-pressure. A study in Go concurrency — channels, contexts, and bounded fan-out.',
    tags:['go','concurrency','scraping'] },
  { id:'heali', repo:'Heali-ai-challenge', eyebrow:'CHALLENGE · 2024', status:'shipped',
    title:'Heali — AI engineering challenge',
    desc:'A take-home for a healthcare AI startup: structured extraction over messy clinical PDFs with citation-grounded outputs. Shipped + interviewed.',
    tags:['llm','extraction','health'] },
  { id:'hibernate', repo:'hibernate-orm', eyebrow:'CONTRIBUTION · 2022', status:'shipped',
    title:'Hibernate ORM — upstream contributions',
    desc:'Patches and bug repros against the canonical Java ORM. Where I learned that "framework code" is just code, and reading it is the fastest way to seniority.',
    tags:['java','open-source','orm'] },
  { id:'auth-expo', repo:'Authorization-App-Expo-Firebase', eyebrow:'PROJECT · 2022', status:'shipped',
    title:'Mobile auth — Expo + Firebase',
    desc:'Reference React Native auth flow with Firebase: email + OAuth, secure token storage, and a clean post-login navigation tree.',
    tags:['react-native','firebase','auth'] },
  { id:'amplify-auth', repo:'create-react-app-auth-amplify', eyebrow:'PROJECT · 2021', status:'shipped',
    title:'CRA + AWS Amplify auth',
    desc:'A web counterpart: Cognito-backed auth in a CRA, with hosted UI, federated identities, and protected routes.',
    tags:['react','aws','cognito'] },
  { id:'aws-concepts', repo:'Aws-Concepts', eyebrow:'STUDY · 2023', status:'shipped',
    title:'AWS Concepts — SAP-C02 study notebook',
    desc:'Deep-dive notes used to pass the AWS Solutions Architect Professional exam. Diagrams, IAM patterns, networking, and the hard parts in one place.',
    tags:['aws','certification','notes'] },
  { id:'spring', repo:'SpringConcepts', eyebrow:'STUDY · 2022', status:'shipped',
    title:'Spring & Spring JPA reference',
    desc:'Working examples covering DI, MVC, Boot, and JPA — built while shipping Java microservices at Mercedes-Benz Financial Services.',
    tags:['java','spring','jpa'] },
  { id:'python-auto', repo:'PythonAutomation', eyebrow:'TOOLBELT · 2022', status:'shipped',
    title:'Python automation toolbelt',
    desc:'Small scripts I keep reaching for: file ops, data wrangling, CLI utilities, and a few things that quietly run in cron.',
    tags:['python','scripts','tooling'] },
  { id:'site', repo:'aakashsethi.github.io', eyebrow:'SITE · 2021', status:'archived',
    title:'aakashsethi.github.io — predecessor site',
    desc:'My first portfolio. Jekyll on GitHub Pages. A useful baseline this design system is replacing.',
    tags:['jekyll','github-pages'] },
  { id:'btb', repo:'backtobackswe', eyebrow:'STUDY · 2021', status:'shipped',
    title:'BackToBackSWE — interview prep',
    desc:'Annotated solutions and patterns from the canonical interview-prep canon. Practice for the loops at Vanguard, MBFS, and beyond.',
    tags:['algorithms','study'] },
  { id:'njit', repo:'NJIT2019', eyebrow:'COURSEWORK · 2019–20', status:'archived',
    title:'NJIT 2019 — graduate coursework',
    desc:'Coursework for the M.S. in Information Systems: web mining, ML, enterprise databases, UX design.',
    tags:['coursework','njit'] },
  { id:'search', repo:'search', eyebrow:'EXPERIMENT · 2022', status:'archived',
    title:'search — IR & ranking experiments',
    desc:'Sandbox for retrieval ideas: BM25 baselines, dense vectors, hybrid scoring, and tiny eval harnesses.',
    tags:['retrieval','ir','experiments'] },
  { id:'props', repo:'UseOfProps', eyebrow:'TEACHING · 2021', status:'shipped',
    title:'Use of Props — React teaching repo',
    desc:'A worked example I use when explaining React props vs state to first-time students. NJDOE-licensed CS teacher; this is the kind of thing I write for that.',
    tags:['react','teaching'] },
  { id:'faq', repo:'FrequentlyAsked', eyebrow:'NOTES · 2022', status:'archived',
    title:'FrequentlyAsked — running Q&A',
    desc:'A long-running notebook of questions students and teammates have asked me. The format I keep returning to: question first, code second.',
    tags:['notes','teaching'] },
];

window.PROJECTS = PROJECTS;
