/* global React */
/* LinkedIn posts feed — reads from /data/linkedin_posts.json (generated by pipeline, no API key in frontend) */
const { useState, useEffect } = React;

function LinkedInFeed() {
  const [posts, setPosts]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState(null);

  useEffect(() => {
    fetch('/data/linkedin_posts.json')
      .then(r => r.json())
      .then(d => { setPosts((d || []).slice(0, 5)); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const timeAgo = (dateStr) => {
    if (!dateStr) return '';
    const diff = Date.now() - new Date(dateStr);
    const h = Math.floor(diff / 3600000);
    const d = Math.floor(h / 24);
    if (d > 0) return `${d}d ago`;
    if (h > 0) return `${h}h ago`;
    return 'just now';
  };

  const preview = (text, n = 180) =>
    text.length > n ? text.slice(0, n).trimEnd() + '…' : text;

  const themeColor = (theme) => {
    const map = {
      ai_engineering: 'var(--signal-500)',
      career:         'var(--ink-400)',
      cloud_aws:      '#f90',
      fintech:        '#26c281',
      product:        '#a78bfa',
      personal_story: 'var(--signal-300)',
      engagement:     '#60a5fa',
    };
    return map[theme] || 'var(--signal-500)';
  };

  return (
    <section className="li-feed">
      <div className="section-header">
        <div>
          <div className="eyebrow">
            <span className="live-dot" /> LinkedIn · auto-updated daily
          </div>
          <h2 className="section-title">Recent Posts</h2>
        </div>
        <a href="https://linkedin.com/in/aakash-sethi-007" target="_blank" rel="noopener" className="btn btn-ghost-dark btn-sm">
          Follow on LinkedIn →
        </a>
      </div>

      {loading && <div className="feed-loading"><div className="spinner" /><span className="muted small">Loading posts…</span></div>}

      {!loading && posts.length === 0 && (
        <div className="feed-placeholder">
          <img src="/assets/ai/linkedin_bg.png" alt="" className="feed-placeholder-img" />
          <p className="muted small" style={{marginTop:'1rem'}}>Posts will appear here once the daily pipeline runs.</p>
        </div>
      )}

      {!loading && posts.length > 0 && (
        <div className="li-list">
          {posts.map((p, i) => (
            <div key={i} className="li-card">
              <div className="li-card-top">
                <span className="li-tag" style={{borderColor: themeColor(p.theme), color: themeColor(p.theme)}}>
                  {(p.theme || 'post').replace('_', ' ')}
                </span>
                <span className="eyebrow">{timeAgo(p.date)}</span>
              </div>
              <p className="li-body">
                {expanded === i ? p.content : preview(p.content)}
              </p>
              <div className="li-card-footer">
                <button className="li-expand" onClick={() => setExpanded(expanded === i ? null : i)}>
                  {expanded === i ? 'Show less ↑' : 'Read more ↓'}
                </button>
                {p.post_url && (
                  <a href={p.post_url} target="_blank" rel="noopener" className="li-link">
                    View on LinkedIn →
                  </a>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}

window.LinkedInFeed = LinkedInFeed;
